<?php


namespace App\Support\Discount\Coupon\Validator;


use App\Exceptions\IllegalCouponException;
use App\Models\Coupon;

class CanUseIt extends Contracts\AbstractCouponValidator
{
    /**
     * @throws IllegalCouponException
     */
    public function validate(Coupon $coupon): bool
    {
        if(!auth()->user()->coupons->contains($coupon)){
            throw new IllegalCouponException();
        }
        return parent::validate($coupon); // TODO: Change the autogenerated stub
    }
}
